Add check that action is valid
Without this, an invalid action results in a hard-to-parse error from
ffcli in the go binary.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -35,6 +35,13 @@ runs:
       run: |
         echo "::error title=⛔ error hint::only one of API Key or OAuth secret should be specified.
         exit 1
+    - name: Check action is valid
+      if: ${{ inputs['action'] != 'test' && inputs['action'] != 'apply' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::action must be either 'test' or 'apply'"
+        exit 1
+
     - uses: actions/setup-go@v5
       with:
         go-version: 1.22.1
